ViewQuestion
linaism/SOEN341 pull request #75
Opened 2021-11-30 23:17 UTC by Anusha-Reddy-Lattupally

#72 Added styling to the pages.

2021-11-30 23:35 UTC, linaism commented on stack-overflow-app/src/Components/NavigationBar.js
> +    const BlueButton = {
Fix indentation for the attributes

2021-11-30 23:35 UTC, linaism commented on stack-overflow-app/src/Components/ViewQuestionPage.js
> +    const upVote= {
Fix indentation for attributes for the three variables

2021-11-30 23:35 UTC, linaism commented on stack-overflow-app/src/Components/ViewQuestionPage.js
> +    const titleText = {fontFamily:'Teko',fontSize:'30px', paddingTop:'40px', color:'#008B8B', paddingLeft:'40px'};
Keep a consistent format; indent the same way as the other variables

2021-11-30 23:35 UTC, linaism commented on stack-overflow-app/src/Components/ViewQuestionPage.js
> +                <h3 style={{fontSize:'15px', fontFamily:'sans-serif', paddingTop:'10px', paddingLeft:'15px'}}> <b>Title: {state.question.title} </b> </h3>
Remove "Title:" and "Content:" since they were placeholders used to identify them and are no longer necessary once styling is applied

2021-12-01 14:42 UTC, Elyes-Bahri approved these changes

2021-12-03 13:53 UTC, Elyes-Bahri approved these changes

2021-12-03 21:40 UTC, linaism requested changes
The margins and padding need to be modified for the view question page

2021-12-12 01:44 UTC, linaism approved these changes

2021-12-12 01:45 UTC, merged